version: '3.7'

services:
  web:
    container_name: ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volumes_data:/data
    ports:
      - 6379:6379

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports: 
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volumes_data:
  redis_insight_volume_data:
